apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test
  namespace: cert-manager
spec:
  secretName: test-certs
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - yogendra inc.
  commonName: yogendra.me
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - localhost
  - example.com
  - www.example.com
  uris:
  - spiffe://cluster.local/ns/cert-manager/sa/example
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    name: mkcert-root-ca
    kind: ClusterIssuer
    group: cert-manager.io
